### PR TITLE
Update README.md to appropriate semester

### PR DESCRIPTION
**Pull request by warrenshen**

### CODE REVIEW

**Comment by negativetwelve** [comment]
should we even include the semester in the readme?

**Comment by warrenshen** [comment]
I'd be up to completely remove it so it's more maintainable - but real talk how did my build fail?

**Comment by negativetwelve** [comment]
lol looks like it passed now?

**Comment by chenhoward** [comment]
All me

**Comment by chenhoward** [comment]
But in all seriousness it's because our whole website relies on the fact roles will be seeded and the original test build script didn't seed the roles which is now fixed

**Comment by chenhoward** [comment]
I'm down to remove the semester.

**Pull request closed without merging**
